### PR TITLE
Add since(Long since) methods to Builders; fix another deserialization bug

### PR DESCRIPTION
**Pull request by thomas4g**
The existing `since(Date since)` methods in the request builders are a bit tricky to work with because they pass a timezone-d date to Disqus, meaning you actually have to construct a Date that's timezone adjusted. 

Adding since(Long since) allows passing a unix timestamp and bypassing the messiness of this.

Additionally, the ThreadDeserializer suffered from the same issue described in #4 and fixed in #5. This fixes that issue too.

### CODE REVIEW

**Comment by anthavio** [comment]
Thanks!

**Comment by thomas4g** [comment]
@anthavio no problem! Are you planning on publishing a new version to the Maven central repos any time soon?

**Comment by anthavio** [comment]
Hi Thomas, it seems that after greasing cogs and wheels that didn't turn for few years, I managed to release and publish 1.0.1 via sonnatype. It should be synced into maven central in few hours or so -> http://repo1.maven.org/maven2/net/anthavio/disquo/disquo-api/
Enjoy!

**Comment by thomas4g** [comment]
@anthavio (apologies for the delay; I was on break) - Wonderful! Thanks much!

**Pull request merged**
